### ISSUE TITLE
Target Improvements

### ISSUE THREAD

**Issue by MarcelineVQ** [allfoxwy/UnitXP_SP3#2]
I am very much enjoying this project and it has allowed me to make some very useful tools.
Would it be easy to add an additional argument for the targeting functions that only selects things your camera can see? The nearest enemy selection checks for line of sight for your character but can still easily select things that are behind you, which is rarely what you want, especially if it's a Tab replacement.
Similarly having it just select things that are in front of your character is a bit limiting which is why having it be things your camera can see, or has line of sight to, seems reasonable.

**Comment by allfoxwy** [comment]
> Would it be easy to add an additional argument for the targeting functions that only selects things your camera can see?

Someone on Discord give same idea to me today. I would look into what could I do. I agree it's better.

**Comment by allfoxwy** [comment]
Should be solved by 2e1685b36d08396971c9e076ecd02dd953a4ebdd
