### ISSUE TITLE
Crash In HFQ When Using Targeting Inside Cave

### ISSUE THREAD

**Issue by OldManAlpha** [allfoxwy/UnitXP_SP3#4]
I've found that using any of the enemy targeting functions in HFQ causes stuttering and often causes crashing when I'm inside the cave part of the dungeon.
![image](https://github.com/user-attachments/assets/856db6d6-2af0-4ebb-b232-3961c7b8c5be)

**Comment by allfoxwy** [comment]
Noted. I currently can not connect to game so might need some time to look into it.

Thanks for reporting.
