### ISSUE TITLE
A lot of Wow errors when PvPing

### ISSUE THREAD

**Issue by Aleksxz** [allfoxwy/UnitXP_SP3#5]
Hi.

First of all, thank you for this mod.
I'm currently experiencing a lot of wow errors in PvP events after I installed this mod. It works great in PvE, never had any issue in Naxx, Bwl, dungeons, etc. 
But when it comes to PvP, when an  enemy player nameplates appear, it's 1/10 chance that I'll get a wow error. It happenned in Alterac, Wsg, and even in Stormwind when someone appeared.

I tried to disable taskbar and system notif, nameplate hiding, etc. Same result.

![stunitxp](https://github.com/user-attachments/assets/9f187450-b504-4b6e-b281-1e1c85e029dc)

I'm using Vanilla fixes + Tweaks, Superwow, Nampower, and pfUI for nameplates. Never had any issue before I installed UnitXP.

Thank you.

**Comment by allfoxwy** [comment]
I need to go those 6 hours AVs to do some test. Thanks for reporting.

**Comment by allfoxwy** [comment]
@Aleksxz Hey could you try this one? It includes a fix but purely comes out from my imagination. (I'm not sure what in the game cause the crash, but I somehow located where it crashes and from that location I made a reasoning)
[possiable-fix-UnitXP_SP3.dll.zip](https://github.com/user-attachments/files/17692163/possiable-fix-UnitXP_SP3.dll.zip)

I just finished 1 AB with no crash.

**Comment by allfoxwy** [comment]
I would wait for input from OP before release. I just finished another warsong.

**Comment by Aleksxz** [comment]
I did two full Alterac Valley, no crashes. Good job sir. Maybe it's a coincidence but I don't think so.

**Comment by allfoxwy** [comment]
Thanks for your testing and contribution on this topic! I would include this fix in a later Release.
